//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public string mime { get; set; }
        public string nombre { get; set; }
        public string extension { get; set; }
        public Nullable<int> tamano { get; set; }
        public Nullable<int> creado { get; set; }
        public int expedienteIid { get; set; }
    
        public virtual expediente expediente { get; set; }
    }
}
