
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sb_admin.web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class evento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public evento()
    {

        this.juzgado_evento = new HashSet<juzgado_evento>();

    }


    public int id { get; set; }

    public int tipo_evento { get; set; }

    public string descripcion_evento { get; set; }

    public System.DateTime fecha_inicio { get; set; }

    public Nullable<int> servicioId { get; set; }

    public Nullable<int> expedienteId { get; set; }

    public Nullable<int> tipo_eventoId { get; set; }



    public virtual expediente expediente { get; set; }

    public virtual servicio servicio { get; set; }

    public virtual tipo_evento tipo_evento1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<juzgado_evento> juzgado_evento { get; set; }

}

}
