
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sb_admin.web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class juzgado_evento
{

    public int id { get; set; }

    public Nullable<int> eventoId { get; set; }

    public Nullable<int> juzgadoId { get; set; }



    public virtual evento evento { get; set; }

    public virtual juzgado juzgado { get; set; }

}

}
