
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sb_admin.web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Navbar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Navbar()
    {

        this.Roles = new HashSet<Roles>();

    }


    public int id { get; set; }

    public string nameOption { get; set; }

    public string controller { get; set; }

    public string action { get; set; }

    public string area { get; set; }

    public string imageClass { get; set; }

    public Nullable<bool> estatus { get; set; }

    public Nullable<bool> activeli { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Roles> Roles { get; set; }

}

}
