//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int MenuId { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Navbar Navbar { get; set; }
        public virtual User User { get; set; }
    }
}
