
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sb_admin.web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class telefono_persona
{

    public int id { get; set; }

    public Nullable<int> personaId { get; set; }

    public Nullable<int> telefonosId { get; set; }



    public virtual persona persona { get; set; }

    public virtual telefono telefono { get; set; }

}

}
